import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/provider/theme-provider";
import { AudioProvider } from "@/components/provider/audio-provider";
import { UserProvider } from "@/components/provider/user-provider";
import { MediaActionProvider } from "@/components/provider/media-action-provider";
import { DisplayProvider } from "@/components/provider/display-provider";
import Header from "./Header";
import { Toaster } from "@/components/ui/toaster";
import { PageProtector } from "./PageProtector";
import { Padding } from "./Padding";
import { AlertSpammer } from "@/components/my-ui/alert-spammer";
import { Background } from "./Background";
import { SongList } from "./SongList";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Search } from "./Search";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fff" },
    { media: "(prefers-color-scheme: dark)", color: "#000" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-y-hidden`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <AlertSpammer>
              <UserProvider>
                <MediaActionProvider>
                  <Search />
                  <Header />
                  <AudioProvider>
                    <DisplayProvider>
                      <Background />
                      <Padding>
                        <SongList />
                        {children}
                      </Padding>
                    </DisplayProvider>
                  </AudioProvider>
                  <PageProtector />
                </MediaActionProvider>
              </UserProvider>
            </AlertSpammer>
            <Toaster />
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
